repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b
    hooks:
      - id: check-added-large-files
        exclude: |
          (?x)^(
            docs/img/scix_hub.png
          )$
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2c8dce6094fa2b4b668e74f694ca63ceffd38614
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
